In [2]:
#Importando a biblioteca
import numpy as np

In [9]:
quantidade_produtos = [10,5,3,8] #Lista
print(type(quantidade_produtos))
custo_produtos = [5,10,2,3] #Lista

array_quantidades = np.array(quantidade_produtos) #Array
array_custos = np.array(custo_produtos)

Faturamento = array_quantidades* array_custos
print(Faturamento)
print(type(Faturamento))

<class 'list'>
[50 50  6 24]
<class 'numpy.ndarray'>


In [15]:
#Gerar um Array automático 
np.arange(10,21) #Sem passo

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
#Gerar um Array com passo 
np.arange(10,20,2) #Sobe de dois em dois 


array([10, 12, 14, 16, 18])

In [ ]:
criar duas listas:
- 5 produtos (apenas inserir valores)
- a primeira lista, custo do produto
- A Segunda lista, o preço de venda
- Desafio: Calcular o lucro de cada produto

In [18]:
5 produtos 
Maca
Banana
Uva
Abacaxi
Melao


SyntaxError: invalid syntax (3270280223.py, line 1)

In [25]:
preco_venda = [10,8,8,7,3]
print(type(quantidade_produtos))
custos_valor = [2,5,3,2,1]

array_qtd = np.array(preco_venda) #Array
array_valor = np.array(custos_valor)

Faturamento = preco_venda-array_valor
print(Faturamento)
print(type(Faturamento))

<class 'list'>
[8 3 5 5 2]
<class 'numpy.ndarray'>


In [ ]:
salarios = np.array([2,3,4,5,6,700])
maior_salarios = np.max(salarios)
print(maior_salarios)


700


In [31]:
medias_salarios = np.mean(salarios)
print(f"{medias_salarios:.2f}")

120.00


In [33]:
minimo_salario = np.min(salarios)
print(minimo_salario)

2


In [32]:
mediana_salarios = np.median(salarios)
print(mediana_salarios)

4.5


In [34]:
desvio = np.std(salarios)
print(desvio)

259.38709811142627


In [ ]:
Criar uma lista de venda por dia 
-Vendas = [10,20,45,5,90]
-Exibir a maior venda 
-Exibir a menor venda 
-Exibir a média de vendas
-Exibir a mediana de vendas

In [3]:
Venda_dia = np.array ([10,20,45,5,90])
maior_salarios = np.max(Venda_dia)
print(maior_salarios)

medias_vendas = np.mean(Venda_dia)
print(f"{medias_vendas:.2f}")


minimo_vendas = np.min(Venda_dia)
print(minimo_vendas)

media_vendas = np.mean(Venda_dia)
print(media_vendas)

mediana_vendas = np.median(Venda_dia)
print(mediana_vendas)

desvio_venda = np.std(Venda_dia)
print(desvio_venda)

90
34.00
5
34.0
20.0
31.20897306865447
